<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/binarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer

In [64]:
df = pd.read_csv('/content/Titanic-Dataset.csv', usecols = ['Age', 'Fare', 'SibSp','Parch', 'Survived'])
df.dropna(inplace = True)

In [65]:
df['Family'] = df['SibSp'] + df['Parch']
df.drop(['SibSp', 'Parch'], axis = 1, inplace = True)

In [66]:
df.head()

   Survived   Age     Fare  Family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [67]:
x = df.drop('Survived', axis = 1)
y = df['Survived']

In [68]:
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [69]:
#  Without Binarization
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
accuracy_score(y_test, y_pred)

0.6293706293706294

In [70]:
np.mean(cross_val_score(DecisionTreeClassifier(), x,y,cv = 10, scoring = 'accuracy'))

np.float64(0.6499217527386542)

In [71]:
# Applying Binzarization
from sklearn.preprocessing import Binarizer

In [72]:
transformer = ColumnTransformer([
    ('bins', Binarizer(copy = False), ['Family'])
], remainder = 'passthrough')

In [73]:
x_train_trf = transformer.fit_transform(x_train)
x_test_trf = transformer.transform(x_test)

In [74]:
pd.DataFrame(x_train_trf, columns = ['Family', 'Age', 'Fare'])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [75]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf, y_train)
y_pred2 = clf.predict(x_test_trf)
accuracy_score(y_test, y_pred2)

0.6153846153846154

In [76]:
x_trf = transformer.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(), x_trf,y,cv = 10, scoring = 'accuracy'))

np.float64(0.6304186228482003)