<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/feature_eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('/content/Social_Network_Ads.csv', usecols=[2,3,4])
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [11]:
x = df.drop(['Purchased'], axis = 1)
y = df['Purchased']

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [13]:
x_train.shape

(280, 2)

In [14]:
x_test.shape

(120, 2)

In [16]:
x_train.head(5)

     Age  EstimatedSalary
92    26            15000
223   60           102000
234   38           112000
232   40           107000
377   42            53000

In [17]:
# STANDARD SCALER
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit the Train set, it will learn the parameters
scaler.fit(x_train)

# Transform train and test sets
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [19]:
# x_train = Dataframe
# After scaling x_train_scaled becomes Numpy array
# Convert to dataframe first

x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = x_test.columns)

In [21]:
# Checking -> Before scaling
np.round(x_train.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean    37.9          69807.1
std     10.2          34641.2
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70500.0
75%     46.0          88000.0
max     60.0         150000.0

In [22]:
# Checking -> After Scaling
np.round(x_train_scaled.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.2              2.3