<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/feature_eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

FEATURE SCALING

In [2]:
df = pd.read_csv('/content/Social_Network_Ads.csv', usecols=[2,3,4])
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/Social_Network_Ads.csv'

In [ ]:
x = df.drop(['Purchased'], axis = 1)
y = df['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [ ]:
x_train.shape

In [ ]:
x_test.shape

In [ ]:
x_train.head(5)

In [3]:
# STANDARD SCALER
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit the Train set, it will learn the parameters
scaler.fit(x_train)

# Transform train and test sets
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

NameError: name 'x_train' is not defined

In [4]:
# x_train = Dataframe
# After scaling x_train_scaled becomes Numpy array
# Convert to dataframe first

x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = x_test.columns)

NameError: name 'x_train_scaled' is not defined

In [5]:
# Checking -> Before scaling
np.round(x_train.describe(),1)

NameError: name 'x_train' is not defined

In [6]:
# Checking -> After Scaling
np.round(x_train_scaled.describe(),1)

NameError: name 'x_train_scaled' is not defined

In [7]:
df1 = pd.read_csv("/content/WineQT.csv", usecols = [3,6,11])
df1.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/WineQT.csv'

In [8]:
x = df1.drop('quality', axis = 1)
y = df1['quality']

NameError: name 'df1' is not defined

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)
x_train.he

NameError: name 'x' is not defined

ENCODING

In [23]:
import numpy as np
import pandas as pd

In [24]:
df = pd.read_csv("/content/customer.csv", usecols = [2,3,4])
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [25]:
x = df.drop('purchased', axis =1)
y = df['purchased']

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [27]:
x_train.shape

(40, 2)

In [28]:
x_test.shape

(10, 2)

In [29]:
# Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
ode = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']])

ode.fit(x_train)

x_train_scaled = ode.transform(x_train)
x_test_scaled = ode.transform(x_test)

In [39]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = x_test.columns)

In [40]:
x_train.head(4)

     review education
8   Average        UG
28     Poor    School
15     Poor        UG
44  Average        UG

In [41]:
x_train_scaled.head(4)

   review  education
0     1.0        1.0
1     0.0        0.0
2     0.0        1.0
3     1.0        1.0

In [42]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(y_train)

y_train_scaled = le.transform(y_train)
y_test_scaled = le.transform(y_test)

In [47]:
y_train.head()

8      No
28     No
15     No
44     No
10    Yes
Name: purchased, dtype: object

In [48]:
y_train_scaled

array([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1])