<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/feature_eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

FEATURE SCALING

In [ ]:
df = pd.read_csv('/content/Social_Network_Ads.csv', usecols=[2,3,4])
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/Social_Network_Ads.csv'

In [ ]:
x = df.drop(['Purchased'], axis = 1)
y = df['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [ ]:
x_train.shape

In [ ]:
x_test.shape

In [ ]:
x_train.head(5)

In [ ]:
# STANDARD SCALER
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit the Train set, it will learn the parameters
scaler.fit(x_train)

# Transform train and test sets
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

NameError: name 'x_train' is not defined

In [ ]:
# x_train = Dataframe
# After scaling x_train_scaled becomes Numpy array
# Convert to dataframe first

x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = x_test.columns)

NameError: name 'x_train_scaled' is not defined

In [ ]:
# Checking -> Before scaling
np.round(x_train.describe(),1)

NameError: name 'x_train' is not defined

In [ ]:
# Checking -> After Scaling
np.round(x_train_scaled.describe(),1)

NameError: name 'x_train_scaled' is not defined

In [ ]:
df1 = pd.read_csv("/content/WineQT.csv", usecols = [3,6,11])
df1.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/WineQT.csv'

In [ ]:
x = df1.drop('quality', axis = 1)
y = df1['quality']

NameError: name 'df1' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)
x_train.he

NameError: name 'x' is not defined

ENCODING

In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("/content/customer.csv", usecols = [2,3,4])
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
x = df.drop('purchased', axis =1)
y = df['purchased']

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [8]:
x_train.shape

(40, 2)

In [9]:
x_test.shape

(10, 2)

In [10]:
# Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder
ode = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']])

ode.fit(x_train)

x_train_scaled = ode.transform(x_train)
x_test_scaled = ode.transform(x_test)

In [11]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = x_test.columns)

In [12]:
x_train.head(4)

   review education
12   Poor    School
17   Poor        UG
10   Good        UG
14   Poor        PG

In [13]:
x_train_scaled.head(4)

   review  education
0     0.0        0.0
1     0.0        1.0
2     2.0        1.0
3     0.0        2.0

In [14]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(y_train)

y_train_scaled = le.transform(y_train)
y_test_scaled = le.transform(y_test)

In [16]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [17]:
y_train.head()

12     No
17    Yes
10    Yes
14    Yes
31    Yes
Name: purchased, dtype: object

In [18]:
y_train_scaled

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [1]:
# One hot encoding
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/content/cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [6]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [7]:
df['brand'].nunique()

32

In [8]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [12]:
df['fuel'].nunique()

4

In [10]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [14]:
df['owner'].nunique()

5

In [51]:
# One Hot Encoding using Pandas
pd.get_dummies(df,columns = ['fuel','owner'], dtype=int)
# first column isnt removed

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [53]:
# n-1 OneHotEncoding
pd.get_dummies(df,columns = ['fuel','owner'], drop_first = True, dtype = int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [17]:
# One hot encoding using Sklearn
x = df.drop('selling_price', axis = 1)
y = df['selling_price']

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [36]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first', sparse_output= False, dtype = np.int32)

In [37]:
ohe.fit(x_train[['fuel','owner']])

OneHotEncoder(drop='first', dtype=<class 'numpy.int32'>, sparse_output=False)

In [40]:
x_train_new = ohe.transform(x_train[['fuel','owner']])
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [41]:
x_train_new.shape

(6502, 7)

In [42]:
np.hstack((x_train[['brand','km_driven']].values, x_train_new))

array([['Hyundai', 60000, 0, ..., 0, 0, 0],
       ['Tata', 150000, 1, ..., 0, 0, 1],
       ['Hyundai', 110000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]], dtype=object)

In [43]:
np.hstack((x_train[['brand','km_driven']].values, x_train_new)).shape

(6502, 9)

In [46]:
# One hot encoding with top categories
df['brand'].value_counts()
df['brand'].nunique()
threshold = 100

In [47]:
count = df['brand'].value_counts()
repl = count[count <= threshold].index

In [50]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype = int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0