<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/multiple_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [108]:
x,y = make_regression(n_samples= 100, n_features=2, n_informative = 2, n_targets = 1, noise=20)

In [109]:
df = pd.DataFrame({'f1':x[:,0],'f2':x[:,1],'target':y})

In [110]:
df.head()

         f1        f2      target
0  0.361594  1.208521  153.027323
1  2.590837  0.227705  172.775089
2  0.812869 -0.005076   46.398042
3 -0.930777 -1.732080 -188.300435
4 -0.818114 -1.744228 -185.829350

In [111]:
fig = px.scatter_3d(df,x='f1',y='f2',z='target')
fig.update_traces(marker=dict(size = 5, color = 'red'))
fig.show()

In [112]:
df.shape

(100, 3)

In [113]:
x = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [114]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [115]:
x_train.head()

          f1        f2
73 -0.503284 -0.845635
12 -2.510374 -0.249469
8   0.206523 -0.735302
4  -0.818114 -1.744228
79  2.171454  1.332813

In [116]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [117]:
y_pred = lr.predict(x_test)

In [118]:
acc = r2_score(y_test,y_pred)
acc1 = mean_absolute_error(y_test,y_pred)
acc2 = mean_squared_error(y_test,y_pred)
print(acc)
print(acc1)
print(acc2)

0.9435907575674194
18.787125946544258
531.6032616350761