<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/p_a_n_d_a_s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

In [24]:
# Series

In [25]:
# String
countries = ['india', 'usa', ' japan','nepal','south korea']
pd.Series(countries[2])

0     japan
dtype: object

In [26]:
# Integer
runs = [32,100,22,1000,567]
pd.Series(runs[3])

0    1000
dtype: int64

In [37]:
# Custom index
gender = ["male","female","male","female","male"]
genders = pd.Series(gender,index=["a","b","c","d","e"])
genders

a      male
b    female
c      male
d    female
e      male
dtype: object

In [38]:
# setting a name
gender_name = pd.Series(gender,index=["a","b","c","d","e"], name = 'GENDER')

In [39]:
# series from dict
marks = {
    'math':67,
    'english':57,
    'odia': 99,
    "japanese": 37
}
mark_series = pd.Series(marks, name ="MARKS")
mark_series

math        67
english     57
odia        99
japanese    37
Name: MARKS, dtype: int64

In [113]:
# series attributes
# size
mark_series.size  # counts missing values
# dtype
genders.dtype
# name
gender_name.name
# is unique
gender_name.is_unique  # gives repetation of items as true or false
# index
mark_series.index
# values
mark_series.values
gender_name.values[0]

'male'

In [134]:
# series using read_csv
# with one column
data = pd.read_csv("/content/car data.csv").squeeze()
car_name = data['Car_Name']
type(car_name)
car_name.head()
# two columns
placement = pd.read_csv("/content/placement.csv", index_col = 'cgpa').squeeze()
placement.head()

cgpa
6.89    3.26
5.12    1.98
7.82    3.25
7.42    3.67
6.94    3.57
Name: package, dtype: float64

In [130]:
# Series methods
# head and tail
placement.head()
car_name.tail()
# sample
placement.sample(5)
# value counts
placement.value_counts().sample()
# sort_values
placement.sort_values(ascending=False).head()   # ascending and descending available, default = True
# sort_index
car_name.sort_index()

0         ritz
1          sx4
2         ciaz
3      wagon r
4        swift
        ...
296       city
297       brio
298       city
299       city
300       brio
Name: Car_Name, Length: 301, dtype: object

In [133]:
# Series maths method
# count
placement.count()  # doesnt count missing values
# sum
placement.sum()
# product
placement.product()
# mean
placement.mean()
# median
placement.median()
# std
placement.std()
# min
placement.min()
# max
placement.max()
# describe
placement.describe()     # gives a overview data of data

count    200.000000
mean       2.996050
std        0.691644
min        1.370000
25%        2.487500
50%        2.995000
75%        3.492500
max        4.620000
Name: package, dtype: float64