<a href="https://colab.research.google.com/github/sj-workbench/years_of_learnings/blob/main/p_a_n_d_a_s1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# Series

In [3]:
# String
countries = ['india', 'usa', ' japan','nepal','south korea']
pd.Series(countries[2])

0     japan
dtype: object

In [4]:
# Integer
runs = [32,100,22,1000,567]
pd.Series(runs[3])

0    1000
dtype: int64

In [5]:
# Custom index
gender = ["male","female","male","female","male"]
genders = pd.Series(gender,index=["a","b","c","d","e"])
genders

a      male
b    female
c      male
d    female
e      male
dtype: object

In [6]:
# setting a name
gender_name = pd.Series(gender,index=["a","b","c","d","e"], name = 'GENDER')

In [7]:
# series from dict
marks = {
    'math':67,
    'english':57,
    'odia': 99,
    "japanese": 37
}
mark_series = pd.Series(marks, name ="MARKS")
mark_series

math        67
english     57
odia        99
japanese    37
Name: MARKS, dtype: int64

In [8]:
# series attributes
# size
mark_series.size  # counts missing values
# dtype
genders.dtype
# name
gender_name.name
# is unique
gender_name.is_unique  # gives repetation of items as true or false
# index
mark_series.index
# values
mark_series.values
gender_name.values[0]

'male'

In [11]:
# series using read_csv
# with one column
data = pd.read_csv("/content/car data.csv").squeeze()
car_name = data['Car_Name']
type(car_name)
car_name.head()
# two columns
placement = pd.read_csv("/content/placement.csv", index_col = 'cgpa').squeeze()
placement.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/car data.csv'

In [ ]:
# Series methods
# head and tail
placement.head()
car_name.tail()
# sample
placement.sample(5)
# value counts
placement.value_counts().sample()
# sort_values
placement.sort_values(ascending=False).head()   # ascending and descending available, default = True
# sort_index
car_name.sort_index()

In [ ]:
# Series maths method
# count
placement.count()  # doesnt count missing values
# sum
placement.sum()
# product
placement.product()
# mean
placement.mean()
# median
placement.median()
# std
placement.std()
# min
placement.min()
# max
placement.max()
# describe
placement.describe()     # gives a overview data of data

In [10]:
# Series indexing

In [32]:
numbers = [12,23,45,64,'SJ']
numbers = pd.Series(numbers, index = ['a','b','c','d','e'], name = "AGE")
numbers[-1]                        # -ve/+ve works

/tmp/ipykernel_6716/2207923887.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  numbers[-1]                        # -ve/+ve works

'SJ'

In [33]:
number = pd.Series([12,'SJ',42,43,21], name = 'House')
number[1]                        # +ve only works

'SJ'

In [40]:
# Series slicing
place = ['japan','south korea', 'LA','London', 'India','Spain', 'Europe','Thailand']
places = pd.Series(place, index = [1,2,3,4,5,6,7,8])
places
place[5::2]
place[::2]

1          japan
2    south korea
3             LA
4         London
5          India
6          Spain
7         Europe
8       Thailand
dtype: object

In [42]:
# fancy indexing
places[[1,4,5]]

1     japan
4    London
5     India
dtype: object

In [48]:
# Editng item inside series
# using indexing
marks = [23,45,65,78,99,76,54]
marks = pd.Series(marks, name = 'mark')
marks[1] = 100   # edited
marks
# what if an index doesnt not exist
marks[7] = 288
marks

0     23
1    100
2     65
3     78
4     99
5     76
6     54
7    288
Name: mark, dtype: int64